# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60cf12e5ee6f3d4869258f031f3dca86cc989eb791a666e2c08f732d4b91f7eb58b036f510fd7fa44e94c939cd14ee38f53fdb3d9ea9cc1069946b55a730e0ab

test:
  secret_key_base: fae1417199e2bf247e0efa23f1968832974c728ac8b078a43bffd67be025d4978eeb2aaa0f4db7dc5e201a18b9167907f8b1d62660468e26d9775d2191675308

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
